Ticket #7115 - Update `setup.py`
 * Move tests.
 * Move and clean locales.
 * Remove duplicate installation files.
 * Update manifest template.

diff --git a/fred-webadmin-server b/fred-webadmin-server
--- a/fred-webadmin-server
+++ b/fred-webadmin-server
@@ -1,76 +1,105 @@
 #!/bin/sh
+# fred-webadmin-server	This is the init script for starting up FRED
+#	                administration web server.
+#
+# chkconfig: - 92 08
+# description: Starts and stops FRED web administration backend daemon
 
-if [ -d /lib/lsb/ ]; then
-    uselsb=1
-else
-    uselsb=0
-fi
-
-if [ $uselsb -eq 1 ]; then
+if [ -f /lib/lsb/init-functions ]; then
     . /lib/lsb/init-functions
+else
+    log_failure_msg() { echo "ERROR: $1"; }
+    log_success_msg() { echo "SUCCESS: $1"; }
 fi
 
+PATH=$PATH:/sbin # to find pidof on redhat
 
 MSG_START="Starting FRED webadmin HTTP server..."
 MSG_STOP="Stopping FRED webadmin HTTP server..."
 
-WEBADMIN_EXEC="DU_PREFIX/sbin/fred-webadmin"
-PIDFILE="DU_PREFIX/var/run/fred-webadmin"
+WEBADMIN_EXEC="DU_WEBADMIN_BIN"
+PIDFILE="DU_LOCALSTATEDIR/run/fred-webadmin"
 
 PATH=$PATH:/sbin
-fred_start() {
-    ${WEBADMIN_EXEC} &
-    if [ $? != 0 ]; then
-        if [ $uselsb -eq 1 ]; then
-            log_failure_msg ${MSG_START}
-        else
-            echo "ERROR: ${MSG_START}"
+
+check_pidfile() {
+    ps -p $(cat $1 2>/dev/null) >/dev/null 2>&1
+}
+
+#
+# Store pid of process described by regex $1 into filename $2
+#
+store_pid()
+{
+    RETRY_COUNT=2
+    PID=""
+    while [ $RETRY_COUNT -gt 0 -a "$PID" = "" ]; do
+        PID=$(ps -e -o "pid args" | sed 's/^ *//g' | \
+        grep  "$1" | grep -v grep | cut -f1 -d' ')
+        if [ "$PID" = "" ]; then
+            RETRY_COUNT=$(($RETRY_COUNT - 1))
+            sleep 1
         fi
+    done
+    if [ "$PID" != "" ]; then
+        echo $PID > $2; /bin/true; return
     else
-        if [ $uselsb -eq 1 ]; then
-            log_success_msg ${MSG_START}
+        test -f $2 && rm $2; /bin/false; return
+    fi
+}
+
+fred_start() {
+    if check_pidfile $PIDFILE; then
+        log_success_msg "${MSG_START}"
+    else
+        ${WEBADMIN_EXEC} >/dev/null 2>&1 &
+        if store_pid "${WEBADMIN_EXEC}" $PIDFILE
+        then
+            log_success_msg "${MSG_START}"
         else
-            echo "SUCCESS: ${MSG_START}"
+            log_failure_msg "${MSG_START}"
         fi
-        PID=$(pidof -o $$ -o $PPID -o %PPID -x "$WEBADMIN_EXEC" || \
-                pidof -o $$ -o $PPID -o %PPID -x "${WEBADMIN_EXEC##*/}")
-        echo "$PID" > $PIDFILE
+    fi
+}
+
+fred_status() {
+    echo -n "fred-webadmin is ";
+    if check_pidfile $PIDFILE
+    then
+        echo "running"
+    else
+        echo "stopped"
     fi
 }
 
 fred_stop() {
-    if [ -f $PIDFILE ]
-    then
-        kill $(cat $PIDFILE)
-        if [ $uselsb -eq 1 ]; then
-            log_success_msg ${MSG_STOP}
-        else
-            echo "ERROR: ${MSG_STOP}"
-        fi
-        rm $PIDFILE
+    kill $(cat $PIDFILE 2>/dev/null) >/dev/null 2>&1
+    if [ $? -eq 0 ]; then
+        log_success_msg "${MSG_STOP}"
+        rm $PIDFILE >/dev/null 2>&1
     else
-        if [ $uselsb -eq 1 ]; then
-            log_failure_msg ${MSG_STOP}
-        else
-            echo "SUCCESS: ${MSG_STOP}"
-        fi
+        log_failure_msg "${MSG_STOP}"
     fi
 }
 
 case "$1" in
-start)
+    start)
         fred_start
-  ;;
-restart)
+        ;;
+    restart)
         fred_stop
         fred_start
-  ;;
-stop)
+        ;;
+    stop)
         fred_stop
-  ;;
-*)
-  echo "Usage: /etc/init.d/fred-webadmin-server {start|stop|restart}"
-  exit 1
+        ;;
+    status)
+        fred_status
+        ;;
+    *)
+        echo -n "Usage: /etc/init.d/fred-webadmin-server "
+        echo "{start|stop|restart|status}"
+        exit 1
 esac
 
 exit 0
